name: Increment Version Code
description: 'Increments the version code in version.properties and commits to main branch'

inputs:
  github-token:
    description: 'GitHub token with write permissions to push to main'
    required: true

outputs:
  previous-version:
    description: "Previous version code"
    value: ${{ steps.increment.outputs.current-version }}
  new-version:
    description: "New version code"
    value: ${{ steps.increment.outputs.new-version }}

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.github-token }}
        ref: main
        fetch-depth: 1

    - name: Increment version code
      id: increment
      shell: bash
      run: |
        # Read current version code
        CURRENT_VERSION=$(grep 'app.versionCode=' version.properties | cut -d'=' -f2)
        echo "Current version code: $CURRENT_VERSION"
        
        # Increment version code
        NEW_VERSION=$((CURRENT_VERSION + 1))
        echo "New version code: $NEW_VERSION"
        
        # Update version.properties file
        sed -i "s/app.versionCode=.*/app.versionCode=${NEW_VERSION}/" version.properties
        
        # Output for logging
        echo "current-version=$CURRENT_VERSION" >> "$GITHUB_OUTPUT"
        echo "new-version=$NEW_VERSION" >> "$GITHUB_OUTPUT"

    - name: Commit and push version increment
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add version.properties
        git commit -m "chore: increment version code to ${{ steps.increment.outputs.new-version }} [skip ci]"
        git push origin main

    - name: Log version increment
      shell: bash
      run: |
        echo "### Version Code Incremented 🚀" >> "$GITHUB_STEP_SUMMARY"
        echo "Previous version: ${{ steps.increment.outputs.current-version }}" >> "$GITHUB_STEP_SUMMARY"
        echo "New version: ${{ steps.increment.outputs.new-version }}" >> "$GITHUB_STEP_SUMMARY"

